### ISSUE TITLE
The main branch does not compile.

### ISSUE THREAD

**Issue by tehphilb** [bizz84/split_view_example_flutter#4]
I can't tell what exactly is wrong but since I followed this tutorial I assume it is related to the use of Riverpod. Also It does not work from this step onwards: 

`
final selectedPageNameProvider = StateProvider<String>((ref) {
  return _availablePages.keys.first;
});
`

![image](https://user-images.githubusercontent.com/49588177/145198038-09b5bb3a-7834-411d-8643-394f8abb374d.png)

**Comment by bizz84** [comment]
@tehphilb I suspect this is a Riverpod issue on Flutter web as it works fine on all other platforms.

Could you open an issue on the Riverpod repo and point to this as an example?

**Comment by tehphilb** [comment]
I reset the Flutter channel from dev to stable and everything works as expected.
Accordingly, I have not linked this, as hopefully in the next released version this should no longer be a problem.
